### ISSUE TITLE
Allow overriding .zshrc templates

### ISSUE THREAD

**Issue by TravisWhitehead** [gantsign/ansible-role-oh-my-zsh#89]
It would be nice if users could override the `.zshrc` template. You can accomplish this by making the contents of `src` a variable. See this PR as an example: https://github.com/geerlingguy/ansible-role-gitlab/pull/89/files

**Comment by freemanjp** [comment]
@TravisWhitehead thanks for raising this feature request.

If you need to customise the `.zshrc` you're better off using a ZSH plugin manager such as [Antigen](http://antigen.sharats.me). I have a couple of Ansible roles for Antigen [gantsign.antigen](https://github.com/gantsign/ansible_role_antigen) and [gantsign.antigen_bundles](https://github.com/gantsign/ansible_role_antigen_bundles). I've been using these instead of the `gantsign.oh-my-zsh` role for more than a year now.

With Antigen you can use Oh My Zsh plugins, or [other open source ZSH plugins](https://github.com/unixorn/awesome-zsh-plugins#plugins), or write your own (these can be hosted on GitHub or installed locally). Each plugin can contain a ZSH script that is effectively included  (sourced) into your `.zshrc` and/or a tab-completion file. I have some ZSH plugins hosted on GitHub https://github.com/gantsign/zsh-plugins you can look at.

So unfortunately I don't plan on implementing your feature request. I recommend you look at the [gantsign.antigen](https://github.com/gantsign/ansible_role_antigen) role instead.
